### ISSUE TITLE
Build.PL warnings

### ISSUE THREAD

**Issue by dha** [drforr/Perl-Mogrify#1]
When I run the Build.PL script, it tells me

----Begin Paste ----

WARNING: the following files are missing in your kit:
    examples/generatestats
    examples/loadanalysisdb
    examples/perlmogrifyrc-conway
    extras/perlmogrify.el
    t/01_policy_config.t
    t/02_policy.t
    t/11_policy_factory.t
    t/12_policy_listing.t
    t/14_policy_parameter_behavior_boolean.t
    t/14_policy_parameter_behavior_enumeration.t
    t/14_policy_parameter_behavior_integer.t
    t/14_policy_parameter_behavior_list_string.t
    t/14_policy_parameter_behavior_string.t
    t/14_policy_parameters.t
    t/20_policy_pod_spelling.d/stop-words.txt
    t/20_policy_pod_spelling.t
    t/20_policy_prohibit_evil_modules.t
    t/20_policy_prohibit_hard_tabs.t
    t/20_policy_prohibit_trailing_whitespace.t
    t/20_policy_require_consistent_newlines.t
    t/20_policy_require_tidy_code.t
    t/20_transformers.t
    xt/author/40_mogrifyize-code.t
    xt/author/41_mogrifyize-transformers.t
    xt/author/42_mogrifyize-tests.t
    xt/author/43_mogrifyize-run-files.t
    xt/author/80_policysummary.t
Please inform the author.

---End Paste----

So, I'm informing you. :-)

**Comment by dha** [comment]
Furthermore, although after that warning it actually creates Build, when I run Build, I get this error

Can't open perl script "t/Variables/RequireLocalizedPunctuationVars.run.PL": No such file or directory
t/Variables/RequireLocalizedPunctuationVars.run.PL failed at /usr/local/lib/perl5/site_perl/5.22.0/Module/Build/Base.pm line 2930.

**Comment by drforr** [comment]
I'm beyond flattered that anyone at _all_ has tried to run this other than your humble author. Would it surprise you to know that I haven't actually _run_ Build.PL at all? I'm going to call it "my sneaky way of making sure people don't accidentally install it before I'm ready to release" rather than "I haven't gotten around to scrapping the build system and replacing it with Dist::Zilla,"

However, the current test suite reads META.\* in order to perform tests, and I was getting false positives when I would add a test .run file and rerun the tests, forgetting to add the boilerplate to META.\* and TransformerList.pod. I've fixed this so instead of .run files I have actual .t files with a bit of boilerplate. I'm focusing on getting the transformers to coexist peacefully and do useful things, when that's done I'll eviscerate the old build system, replace it with Dist::Zilla, change the app to something more self-explanatory like Perl::ToPerl6 and release to CPAN.

**Comment by dha** [comment]
Heh. Well, I may give it a shot again tomorrow, and if that doesn't work, I'll wait until you tell me it's more fully baked. :-)

**Comment by drforr** [comment]
The current version _does_ run the full test suite cleanly, I might just dump this onto CPAN tonight.

**Comment by dha** [comment]
Ok, will try to remember to build in the am.
